### ISSUE TITLE
exc_bad_instruction

### ISSUE THREAD

**Issue by zoeyin** [Mav3r1ck/Project-RainMan#1]
let pm = placemarks[0] as! CLPlacemark in func locationManager

**Comment by Aaron-A-zz** [comment]
Hello zoeyin, 

Thanks for opening up an issue. Can you tell me more about it?

**Comment by zoeyin** [comment]
Hi Aaron
A little bit late. I did have the problem in func locationManager."let pm = placemarks[0] as! CLPlacemark"
But it’s good now and I have no idea what cause that. I’m really new with Swift and IOS develop.
But still thanks a lot.

Zoe
