### ISSUE TITLE
userLocationLabel values are not unwrapped

### ISSUE THREAD

**Issue by rluftw** [Mav3r1ck/Project-RainMan#4]
Hey Aaron,

I was just testing out the app and I noticed that the user locations were being shown as optional values. I'm not sure if this was done intentionally, but It's on line 163 of the ViewController.swift file.

``` swift
self.userLocationLabel.text = "\(locality!), \(administrativeArea!)"
```

Cheers,
Richard

**Comment by dhamaniasad** [comment]
@Mav3r1ck 
It seems like this issue still persists. This is the code:

``` swift
let locality = (containsPlacemark.locality != nil) ? containsPlacemark.locality : ""
let administrativeArea = (containsPlacemark.administrativeArea != nil) ? containsPlacemark.administrativeArea : ""
```

Changing it to the below resolves the issue with 'Optional("City"), Optional("State")' being displayed to the user.

``` swift
let locality = (containsPlacemark.locality != nil) ? containsPlacemark.locality! : ""
let administrativeArea = (containsPlacemark.administrativeArea != nil) ? containsPlacemark.administrativeArea! : ""
```

I'd be happy to open a PR for this change.
